name: workflow automation cron job

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  make-contribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Configure Git User
        run: |
          git config --global user.name "gainfisheries"
          git config --global user.email "gainfisheries@gmail.com"

      - name: Remove README.md
        run: |
          git rm -f README.md || true

      - name: Make daily contribution
        run: |
          echo "Making daily contribution"
          echo "$(date)" >> README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: "gainfisheries"
          author_email: "gainfisheries@gmail.com"
          message: "Daily contribution"
          add: "README.md"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: daily-contribution
          github_token: ${{ secrets.gh }}
      
      - name: Open pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Daily Contribution"
          commit-message: "Daily contribution"
          branch: daily-contribution
          base: main
          body: "This pull request was created automatically by a GitHub Actions workflow to make a daily contribution."
          token: ${{ secrets.gh }}
